apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-nfs
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # Once the server is created, you'd need to get the cluster IP (`kubectl get service`) and copy it here
    server: 172.21.200.2 #nfs-server.po-odh-project.svc 
    path: "/"

