#Adapted from https://gist.github.com/protosam/05529f26fbc2b7be3ad28d7022729d43
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine:latest
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: nvme
            mountPath: /data
        env:
          - name: SHARED_DIRECTORY
            value: /data
      volumes:
      - name: nvme
        hostPath:
          path: /var/data/ # Modify this depending on where the nvme ssd is mounted
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: default
spec:
  type: ClusterIP
  clusterIP: 172.21.200.2
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
